name = "twitterworker"
node_compat = true
main = "index.js"
compatibility_date = "2022-08-16"

account_id = "e4e117e43dcd195f5ab2207218d22932"
workers_dev = true

[triggers]
crons = [ "14 22 * * *" ]



# wrangler secrets:
# TWITTER_API_KEY
# TWITTER_API_SECRET
# TWITTER_ACCESS_TOKEN
# TWITTER_ACCESS_SECRET